### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by codelast** [astooke/rlpyt#146]
Hi, I run my codes(Using rlpyt GpuSampler) on a GPU machine, which has CUDA installed:

> # nvidia-smi
> NVIDIA-SMI 410.72       Driver Version: 410.72       CUDA Version: 10.0

but I got "AssertionError: Torch not compiled with CUDA enabled" error.

By the way, here is how my Anaconda rlpyt env installed:

> conda env create -f linux_cuda10.yml

Anyone knows why this happened? Thanks a lot.

**Comment by codelast** [comment]
Figured out why.
Modify following line in linux_cuda10.yml:

> cudatoolkit=10.

to:

> cudatoolkit=10.0

Then problem solved.

> conda list | grep pytorch

will see that PyTorch is GPU version.
